/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as GoldRouteImport } from './routes/gold'
import { Route as SilverRouteImport } from './routes/silver'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAddUserRouteImport } from './routes/admin/add-user'
import { Route as AdminHistoryRouteImport } from './routes/admin/history'
import { Route as AdminIncomeRouteImport } from './routes/admin/income'
import { Route as AdminKycRouteImport } from './routes/admin/kyc'
import { Route as AdminPayoutRouteImport } from './routes/admin/payout'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardIncomeRouteImport } from './routes/dashboard/income'
import { Route as DashboardKycRouteImport } from './routes/dashboard/kyc'
import { Route as DashboardLeaderboardRouteImport } from './routes/dashboard/leaderboard'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardTeamRouteImport } from './routes/dashboard/team'
import { Route as DashboardTreeRouteImport } from './routes/dashboard/tree'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldRoute = GoldRouteImport.update({
  id: '/gold',
  path: '/gold',
  getParentRoute: () => rootRouteImport,
} as any)
const SilverRoute = SilverRouteImport.update({
  id: '/silver',
  path: '/silver',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAddUserRoute = AdminAddUserRouteImport.update({
  id: '/add-user',
  path: '/add-user',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHistoryRoute = AdminHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIncomeRoute = AdminIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKycRoute = AdminKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutRoute = AdminPayoutRouteImport.update({
  id: '/payout',
  path: '/payout',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIncomeRoute = DashboardIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardKycRoute = DashboardKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLeaderboardRoute = DashboardLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeamRoute = DashboardTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTreeRoute = DashboardTreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/gold': typeof GoldRoute
  '/silver': typeof SilverRoute
  '/admin/add-user': typeof AdminAddUserRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/income': typeof AdminIncomeRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/payout': typeof AdminPayoutRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/income': typeof DashboardIncomeRoute
  '/dashboard/kyc': typeof DashboardKycRoute
  '/dashboard/leaderboard': typeof DashboardLeaderboardRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/tree': typeof DashboardTreeRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/gold': typeof GoldRoute
  '/silver': typeof SilverRoute
  '/admin/add-user': typeof AdminAddUserRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/income': typeof AdminIncomeRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/payout': typeof AdminPayoutRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/income': typeof DashboardIncomeRoute
  '/dashboard/kyc': typeof DashboardKycRoute
  '/dashboard/leaderboard': typeof DashboardLeaderboardRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/tree': typeof DashboardTreeRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/gold': typeof GoldRoute
  '/silver': typeof SilverRoute
  '/admin/add-user': typeof AdminAddUserRoute
  '/admin/history': typeof AdminHistoryRoute
  '/admin/income': typeof AdminIncomeRoute
  '/admin/kyc': typeof AdminKycRoute
  '/admin/payout': typeof AdminPayoutRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/income': typeof DashboardIncomeRoute
  '/dashboard/kyc': typeof DashboardKycRoute
  '/dashboard/leaderboard': typeof DashboardLeaderboardRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/team': typeof DashboardTeamRoute
  '/dashboard/tree': typeof DashboardTreeRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/gold'
    | '/silver'
    | '/admin/add-user'
    | '/admin/history'
    | '/admin/income'
    | '/admin/kyc'
    | '/admin/payout'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/income'
    | '/dashboard/kyc'
    | '/dashboard/leaderboard'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/reports'
    | '/dashboard/team'
    | '/dashboard/tree'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/gold'
    | '/silver'
    | '/admin/add-user'
    | '/admin/history'
    | '/admin/income'
    | '/admin/kyc'
    | '/admin/payout'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/income'
    | '/dashboard/kyc'
    | '/dashboard/leaderboard'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/reports'
    | '/dashboard/team'
    | '/dashboard/tree'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/dashboard'
    | '/gold'
    | '/silver'
    | '/admin/add-user'
    | '/admin/history'
    | '/admin/income'
    | '/admin/kyc'
    | '/admin/payout'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/dashboard/income'
    | '/dashboard/kyc'
    | '/dashboard/leaderboard'
    | '/dashboard/notifications'
    | '/dashboard/profile'
    | '/dashboard/reports'
    | '/dashboard/team'
    | '/dashboard/tree'
    | '/admin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  GoldRoute: typeof GoldRoute
  SilverRoute: typeof SilverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold': {
      id: '/gold'
      path: '/gold'
      fullPath: '/gold'
      preLoaderRoute: typeof GoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/silver': {
      id: '/silver'
      path: '/silver'
      fullPath: '/silver'
      preLoaderRoute: typeof SilverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/add-user': {
      id: '/admin/add-user'
      path: '/add-user'
      fullPath: '/admin/add-user'
      preLoaderRoute: typeof AdminAddUserRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/history': {
      id: '/admin/history'
      path: '/history'
      fullPath: '/admin/history'
      preLoaderRoute: typeof AdminHistoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/income': {
      id: '/admin/income'
      path: '/income'
      fullPath: '/admin/income'
      preLoaderRoute: typeof AdminIncomeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kyc': {
      id: '/admin/kyc'
      path: '/kyc'
      fullPath: '/admin/kyc'
      preLoaderRoute: typeof AdminKycRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payout': {
      id: '/admin/payout'
      path: '/payout'
      fullPath: '/admin/payout'
      preLoaderRoute: typeof AdminPayoutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/income': {
      id: '/dashboard/income'
      path: '/income'
      fullPath: '/dashboard/income'
      preLoaderRoute: typeof DashboardIncomeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/kyc': {
      id: '/dashboard/kyc'
      path: '/kyc'
      fullPath: '/dashboard/kyc'
      preLoaderRoute: typeof DashboardKycRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/leaderboard': {
      id: '/dashboard/leaderboard'
      path: '/leaderboard'
      fullPath: '/dashboard/leaderboard'
      preLoaderRoute: typeof DashboardLeaderboardRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/team': {
      id: '/dashboard/team'
      path: '/team'
      fullPath: '/dashboard/team'
      preLoaderRoute: typeof DashboardTeamRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tree': {
      id: '/dashboard/tree'
      path: '/tree'
      fullPath: '/dashboard/tree'
      preLoaderRoute: typeof DashboardTreeRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAddUserRoute: typeof AdminAddUserRoute
  AdminHistoryRoute: typeof AdminHistoryRoute
  AdminIncomeRoute: typeof AdminIncomeRoute
  AdminKycRoute: typeof AdminKycRoute
  AdminPayoutRoute: typeof AdminPayoutRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAddUserRoute: AdminAddUserRoute,
  AdminHistoryRoute: AdminHistoryRoute,
  AdminIncomeRoute: AdminIncomeRoute,
  AdminKycRoute: AdminKycRoute,
  AdminPayoutRoute: AdminPayoutRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardIncomeRoute: typeof DashboardIncomeRoute
  DashboardKycRoute: typeof DashboardKycRoute
  DashboardLeaderboardRoute: typeof DashboardLeaderboardRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardTeamRoute: typeof DashboardTeamRoute
  DashboardTreeRoute: typeof DashboardTreeRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIncomeRoute: DashboardIncomeRoute,
  DashboardKycRoute: DashboardKycRoute,
  DashboardLeaderboardRoute: DashboardLeaderboardRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardTeamRoute: DashboardTeamRoute,
  DashboardTreeRoute: DashboardTreeRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRouteWithChildren,
  GoldRoute: GoldRoute,
  SilverRoute: SilverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
